# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: >
      curl --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from 'ramyanairsr@gmail.com' --mail-rcpt 'Ramya.Rajitha@ust-global.com' 
      -T mail.txt --user 'ramyanairsr@gmail.com:Ramyajiv3$' --insecure

